# Setup
title:               DF&V Lab
#tagline:             'A Jekyll theme'
#description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:         "Digital Forensics & Vulnerability Research Laboratory"
url:                 http://dfv-lab.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              DF&V
#  url:               https://twitter.com/mdo
  email:             dohyun.daiel.kim@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
